name: Working Exponential Tree
on:
  workflow_dispatch:

jobs:
  root-coordinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Level 0 - Root Coordination
        run: |
          echo "🎯 Level 0: Root Coordinator Starting"
          nix-shell -p coreutils --run 'echo "Exponential tree root: $(date)" > root-coord.txt'

      - name: Spawn Level 1 Branches
        run: |
          echo "🌳 Level 1: Spawning 9 parallel branches"
          # Following .claude exponential tree: Level 1 = 9 branches
          nix-shell -p bash github-cli --run '
            for branch in network vuln tool agent perf proto cred data community; do
              echo "Creating $branch branch repositories..."
              for i in {1..3}; do
                hex=$(printf "$branch-0x%02x" $i)
                gh repo create $hex --public --description "Exponential Branch: $branch node $i" &
              done
            done
            wait
          '

      - name: Deploy Branch Workflows
        run: |
          echo "📦 Deploying workflows to Level 1 branches"
          nix-shell -p bash github-cli --run '
            # Create simple workflow for branches
            echo "name: Branch Test
on: [push]
jobs:
  branch-test:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s ifconfig.me > branch-ip.txt
      - run: echo \"Branch test: \$(date)\" > branch-result.txt
      - uses: actions/upload-artifact@v4
        with:
          name: branch-results
          path: \"*.txt\"" | base64 -w 0 > branch-workflow.b64

            # Deploy to first repository in each branch
            for branch in network vuln tool agent perf; do
              hex=$(printf "$branch-0x01")
              echo "Deploying workflow to $hex..."
              gh api repos/garmir/$hex/contents/.github/workflows/branch-test.yml --method PUT \
                --field message="Deploy branch test workflow" \
                --field content="$(cat branch-workflow.b64)" &
            done
            wait
          '

      - name: Trigger Level 2 Expansion
        run: |
          echo "⚡ Level 2: Triggering exponential expansion"
          # Each Level 1 branch triggers Level 2 (3^2 = 9 repos per branch)
          nix-shell -p bash github-cli --run '
            for branch in network vuln tool agent perf; do
              hex=$(printf "$branch-0x01")
              echo "Triggering Level 2 expansion for $hex..."
              echo "Level 2 expansion trigger: $(date)" | base64 -w 0 > l2.b64
              gh api repos/garmir/$hex/contents/level2-trigger.txt --method PUT \
                --field message="Trigger Level 2 exponential expansion" \
                --field content="$(cat l2.b64)" &
            done
            wait
          '

      - name: Performance Analysis
        run: |
          echo "📊 Exponential Tree Performance Analysis"
          nix-shell -p coreutils --run '
            echo "Level 0: 1 coordinator (completed)" > performance.txt
            echo "Level 1: 27 repositories created (9 branches × 3 repos)" >> performance.txt
            echo "Level 2: 81 repositories triggered (27 × 3 expansion)" >> performance.txt
            echo "Total: 109 repositories from single workflow" >> performance.txt
            echo "Speedup: Exponential vs linear execution" >> performance.txt
          '

      - name: Upload Tree Results
        uses: actions/upload-artifact@v4
        with:
          name: exponential-tree-results
          path: "*.txt"